/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Connexion;
  GtkWidget *MonProfile;
  GtkWidget *EspaceAdmin;
  GtkWidget *Reservations;
  GtkWidget *Services;
  GtkWidget *citoyens;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Connexion = create_Connexion ();
  gtk_widget_show (Connexion);
  MonProfile = create_MonProfile ();
  gtk_widget_show (MonProfile);
  EspaceAdmin = create_EspaceAdmin ();
  gtk_widget_show (EspaceAdmin);
  Reservations = create_Reservations ();
  gtk_widget_show (Reservations);
  Services = create_Services ();
  gtk_widget_show (Services);
  citoyens = create_citoyens ();
  gtk_widget_show (citoyens);

  gtk_main ();
  return 0;
}

